minimumReleaseAgeExclude:
  - '@vue/compiler-core@3.5.39'
  - '@vue/compiler-dom@3.5.39'
  - '@vue/compiler-sfc@3.5.39'
  - '@vue/compiler-ssr@3.5.39'
  - '@vue/reactivity@3.5.39'
  - '@vue/runtime-core@3.5.39'
  - '@vue/runtime-dom@3.5.39'
  - '@vue/server-renderer@3.5.39'
  - '@vue/shared@3.5.39'
  - vue@3.5.39
